config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :buddies, only: [:index, :show] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:destroy]
  # resources :users, only: [:new, :create, :destroy, :update, :edit]
  get "dashboard", to: 'pages#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :buddy

  validates :starts_at, :ends_at, :request_message, presence: true
  validates :request_message, length: { minimum: 30 }
end

app/models/buddy.rb
class Buddy < ApplicationRecord
  has_many :bookings

  validates :name, :age, :gender, :city, :biography, :hobby, :language, presence: true
  validates :biography, length: { minimum: 150 }
  validates :age, numericality: { only_integer: true }

  include PgSearch::Model
  pg_search_scope :search_by_city_and_hobby,
    against: [ :city, :hobby ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: :destroy
  before_action :set_buddy, only: [:new, :create]

  def index
    @bookings = Booking.all
    @user = User.find(params[:user_id])
  end

  def show
    @booking = User.find(params[:id])
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.buddy = @buddy
    @booking.user = current_user
    if @booking.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def destroy
    @booking.destroy
    redirect_to dashboard_path
  end

  private

  def booking_params
    params.require(:booking).permit(:request_message, :starts_at, :ends_at, :buddy_id)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_buddy
    @buddy = Buddy.find(params[:buddy_id])
  end
end

app/controllers/buddies_controller.rb
class BuddiesController < ApplicationController
  def index
    if params[:search].present?
      @buddies = Buddy.search_by_city_and_hobby(params[:search])
    else
      @buddies = Buddy.all
    end
  end

  def show
    @buddy = Buddy.find(params[:id])
    # @review = Review.new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def dashboard
    @bookings = Booking.where(user: current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div>
  <%= simple_form_for [@buddy, @booking], html: { class: "d-flex justify-content-between"} do |f| %>
    <div class="message_request">
      <%= f.input :request_message %>
      <%= f.input :starts_at %>
      <%= f.input :ends_at %>
    </div>
    <div class='button_position'>
      <%= f.submit class:"btn btn-primary btn-lg" %>
    </div>
  <% end %>
</div>

app/views/buddies/index.html.erb
<% if params[:search].present? %>
  <h2>Your result for <%= params[:search] %></h2>
<% else %>
  <h2>All buddies</h2>
<% end %>

<div class="grid">
  <% @buddies.each do |buddy| %>
    <%= link_to buddy_path(buddy) do %>
      <div class="buddy-card">
        <div>
          <%= image_tag buddy.photo, class: 'card-img' %>
          <h5 class="price">€<%= buddy.price_hour %></h5>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= buddy.name %></h5>
          <p class="card-text"><%= buddy.hobby %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/buddies/show.html.erb
<div class="d-flex justify-content-between">
  <div class="profil-display">
    <h2><%= @buddy.name %></h2>
    <p>I'm <%= @buddy.age %> years old.</p>
    <br>
    <p>I identify myself as <%= @buddy.gender %></p>
    <br>
    <p>I'm leaving in <%= @buddy.city %></p>
    <br>
    <p>A bit about myself: </p>
    <p><%= @buddy.biography %></p>
    <br>
    <p>I enjoy the <%= @buddy.hobby %></p>
  </div>
  <div class="image_button">
    <%= image_tag @buddy.photo, class: 'img-circle' %>
    <button type="button" class="btn btn-primary btn-lg"><%= link_to "Book this buddy", new_buddy_booking_path(@buddy)%></button>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentABuddy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <div class="RAB-container">
        <div class="navbar-menu-application">
          <div class="logo-and-menu-app">
            <h1  class="logo-font logo-font-app"><a href="/"> Rent a buddy </a> </h1>
            <div class="buddy-search-app">
              <form action="<%= buddies_path %>" class="location-text">
                <input name="search" class="location-text" type="text" placeholder="Location or hobby">
              </form>
              <div>
                <button class="search-button"><i class="search-icon fa fa-search"></i></button>
              </div>
            </div>
            <div class="right-side-menu">
              <p> Become a buddy <p>
              <div class="lang-circle">
                <p>EN</p>
              </div>
              <div>
                <a href="/dashboard"><img src="https://cdn.pixabay.com/photo/2016/12/13/05/15/puppy-1903313_960_720.jpg" alt="dogo" class="profile-icon"></a>
              </div>
            </div>
          </div>
        </div>


        <% if action_name === "home" %>
        <div class= site-container-body>
        <div class="site-container-home">
        <% else %>
        <div class="site-container">
        <% end %>
          <%= yield %>
        </div>
        </div>
        </div>

        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>

        <%# <div id="footer">
          <div class="footer-content">
            <div class="info">
              <p>Contact us</p>
              <p>About</p>
            </div>
            <div class="social-media">
              <i class="fab fa-facebook-f"></i>
              <i class="fab fa-twitter"></i>
              <i class="fab fa-instagram"></i>
              <i class="fab fa-linkedin-in"></i>
              <i class="fab fa-youtube"></i>
              <i class="fab fa-github"></i>
            </div>
          </div>
        </div> %>
      </div>
  </body>
</html>

app/views/pages/dashboard.html.erb
<h1>Welcome <%= current_user.username %>!</h1>
<h4> These are your bookings:</h4>
<div class="bookings">
  <% @bookings.reverse_each do |booking| %>
    <div class="confirmation-container">
      <div class="confirmation-photo"><%= image_tag booking.buddy.photo, class: "image" %></div>
      <div class="confirmation-buddy"><%= booking.buddy.name %></div>
      <div class="confirmation-date">
        <p><%= booking.starts_at.strftime("%B %d %Y, %l:%M %P")%></p>
        <p>-</p>
        <p><%= booking.ends_at.strftime("%B %d %Y, %l:%M %P")%></p>
      </div>
      <div class="message-scroll">
        <div class="confirmation-message"><%= booking.request_message%></div>
      </div>
      <div class="confirmation-action"><%= link_to ('<i class="fa fa-trash fa-lg"></i>').html_safe, booking_path(booking), method: :delete, class: "btn btn-cancel", data: { confirm: "Are you sure you want to delete this booking?" } %></div>
    </div>
  <% end %>
</div>
<div id="footer">
  <div class="footer-content">
    <div class="info">
      <p>Contact us</p>
      <p>About</p>
    </div>
    <div class="social-media">
      <i class="fab fa-facebook-f"></i>
      <i class="fab fa-twitter"></i>
      <i class="fab fa-instagram"></i>
      <i class="fab fa-linkedin-in"></i>
      <i class="fab fa-youtube"></i>
      <i class="fab fa-github"></i>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="homepage-container">
  <div class="homepage-background">
    <img class="homepage-image-left" src="https://images.unsplash.com/photo-1542404793-000981fc51f4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80">
    <img class="homepage-image-2" src="https://images.unsplash.com/photo-1524087460115-e21f419c9e1e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80">
    <img class="homepage-image-3" src="https://cdn.pixabay.com/photo/2017/08/01/20/52/people-2567915_960_720.jpg">
    <img class="homepage-image-4" src="https://media.istockphoto.com/photos/happy-soccer-players-with-ball-talking-on-field-picture-id901571932?b=1&k=20&m=901571932&s=170667a&w=0&h=nwk9BiFAaT21Ca8UWKi1_ZIzDRcAlPIoOUqMG5TETkM=">
  </div>
  <div class="home-button">
    <h1 class="button-browse"><%= link_to "Browse all buddies", buddies_path %></h1>
  </div>
</div>
<div id="footer">
  <div class="footer-content">
    <div class="info">
      <p>Contact us</p>
      <p>About</p>
    </div>
    <div class="social-media">
      <i class="fab fa-facebook-f"></i>
      <i class="fab fa-twitter"></i>
      <i class="fab fa-instagram"></i>
      <i class="fab fa-linkedin-in"></i>
      <i class="fab fa-youtube"></i>
      <i class="fab fa-github"></i>
    </div>
  </div>
</div>